### ISSUE TITLE
UI Karma testing. There is no info about in which line error occurs 

### ISSUE THREAD

**Issue by MirekSz** [softwaremill/bootzooka#102]
When I create simple error like this
In PrifleCOntroller I changed 
```
 it('should get logged user', () => {
        expect(scope.user.login).toBe(undefined);//orginal expect(scope.user.login).toBe(userSessionService.getLoggedUser().login);
        expect(scope.user.email).toBe(userSessionService.getLoggedUser().email);
    });
```
but in error there is no right line number
`PhantomJS 2.1.1 (Linux 0.0.0) Profile Controller should get logged user FAILED
        Expected 'user1' to be undefined.
        /baa/bootzooka/ui/test/tests.webpack.js:3647:39
`

**Comment by belfz** [comment]
Hello,

Thank you for pointing this out. It has been just fixed (in 61102be) and merged into master.

Enjoy!
