### ISSUE TITLE
set command renameProject seems to be broken

### ISSUE THREAD

**Issue by aywengo** [softwaremill/bootzooka#105]
`$ git reset --hard HEAD; git clean -d -f
HEAD is now at 7c59246 Docs info
Removing project/project/

$ sbt renameProject com.mycompany foobar
[info] Loading project definition from /Repository/bootzooka/project
[info] Compiling 1 Scala source to /Repository/bootzooka/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to bootzooka (in build file:/Repository/bootzooka/)
[error] renameProject usage:
[error]   renameProject <package> <name>   Replace default name and root package name with your own
[error] 
[error] renameProject
[error]              ^
`

**Comment by adamw** [comment]
This should be `sbt "renameProject com.mycompany foobar"`. Fixed in the docs :)
