### ISSUE TITLE
Angular2 version

### ISSUE THREAD

**Issue by Krever** [softwaremill/bootzooka#109]
Hi there,

have you any plans of releasing Bootzooka with Angular2 instead of Angular.js? 

I was planning to create very similar project(almost exactly the same purpose and stack, akka-http, angular2, webpack) when I found Bootzooka. 
Would you prefer me to keep it as a separate project or to make a pull request to Bootzooka?  

Best

**Comment by belfz** [comment]
Hello,

We are not planning to deprecate Angular.js version of bootzooka yet (it is still widely used). Creating a separate project might be a good option.

Cheers,
Marcin

**Comment by Krever** [comment]
Thanks, so be it.
