### ISSUE TITLE
Better password hashing

### ISSUE THREAD

**Issue by 0xdevalias** [softwaremill/bootzooka#114]
Looking in [User.scala (ln 31-37)](https://github.com/softwaremill/bootzooka/blob/master/backend/src/main/scala/com/softwaremill/bootzooka/user/domain/User.scala#L31-L37) I can see you're using `PBKDF2WithHmacSHA1` with `10,000` rotations. By my understanding, in 2016, SHA1 is a pretty dated choice for this. At the very least, it should probably be `SHA256`.. though both `SHA256` and `SHA512` are vulnerable to length extension attacks. So `SHA384` would be a better choice, or even a `SHA-3` hash; if sticking to SHA.

Other good alternatives to look into would be [Argon2](https://password-hashing.net/#argon2) (winner of the password hashing competition) or [BLAKE2](https://blake2.net/) (combined in a proper way to be useful for password hashing. I believe Argon uses a version of this anyway).

This is a pretty good read on the subject:
* https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016

Other refs:
* http://stackoverflow.com/questions/19348501/pbkdf2withhmacsha512-vs-pbkdf2withhmacsha1

**Comment by adamw** [comment]
Done in #114, thanks for the tip!

**Comment by adamw** [comment]
#120, sorry ;)
