### ISSUE TITLE
Inconsisienct Scala verions in CI

### ISSUE THREAD

**Issue by Pask423** [softwaremill/bootzooka#762]
As for now it seems like we have inconsistency in used Scala versions.
We are using `2.13.7` in `build.sbt` while  `2.12.14` is used in CI
![image](https://user-images.githubusercontent.com/59844835/147394894-26b35471-818a-4e3b-ba50-8437c4c3c2f7.png)

**Comment by adamw** [comment]
The scala version used for running sbt itself is something different than the scala version used in the project.
