### ISSUE TITLE
Use Scala 3

### ISSUE THREAD

**Issue by adamw** [softwaremill/bootzooka#799]
What would we need to make this happen?

One thing is autowire (cc @mbore ), anything else?

**Comment by Pask423** [comment]
Nothing comes to my mind at least if all libs supports Scala3, anyway we can try

**Comment by Pask423** [comment]
As for now I found two problems 
1 `sbt-heroku` has `scala-compiler` in dependencies and it breaks on update to scala3
There is pending fix for this https://github.com/heroku/sbt-heroku/pull/57
2 We are using `macrosautocats` (build.sbt:86) which seems not to support scala3

**Comment by adamw** [comment]
Ad 2 -> see https://github.com/softwaremill/macwire/issues/185

**Comment by Pask423** [comment]
Grate thanks ! Now we just have to wait :stuck_out_tongue:

**Comment by adamw** [comment]
Or implement in macwire ;-)

**Comment by Pask423** [comment]
Hmmm, maybe a good task for next week we will see

**Comment by costa100** [comment]
Any plans to finish the conversion of bootzooka to scala 3? 

Thank you

**Comment by costa100** [comment]
Just curious, are you going to keep the same tech stack: http4s (http server), macwire (DI), doobie (database access) etc.? 
I am starting a new personal project with htt4s & postgres db access with doobie. I want to use scala 3 (there is no point in using scala 2.13 at this point). I was very tempted to use bootzooka but it is using scala 2.13.

**Comment by adamw** [comment]
Yes, I think we'd use the same stack: http4s+tapir, doobie, macwire.
