### ISSUE TITLE
Tagging/'stable' releases?

### ISSUE THREAD

**Issue by alias1** [softwaremill/bootzooka#88]
It would be cool if there were stable releases/version tagging, at least so much as knowing where the last 'stable' point is before a major tech/architecture shift (eg mongo -> slick, scalatra -> akka-http, etc)

**Comment by adamw** [comment]
Yes and no - generally every commit, if it passes unit & integration (selenium) tests should be good to use.

But I agree that for major changes that would be useful - we'll do that in the future. I added a `last-scalatra` tag before the akka http changes

**Comment by alias1** [comment]
Awesome :) Thanks!



—
