### ISSUE TITLE
Add swagger API doco back in

### ISSUE THREAD

**Issue by alias1** [softwaremill/bootzooka#91]
The old scalatra code had support for swagger API doco, but it seems this was lost in the transition to akka-http. It would be cool to have it back.

Not sure how stable/usable these libs are, but:
- https://groups.google.com/forum/#!topic/swagger-swaggersocket/ydDm9esFtEY
- https://github.com/Tecsisa/akka-http-swagger
- https://github.com/devsprint/akka-http-swagger

**Comment by adamw** [comment]
Well there's a general problem with Spray/Akka HTTP and Swagger as the routes are quite dynamic, and in general it's not possible to generate documentation automatically. So you need to use annotations which I find quite ugly ... anyway, we'll see if there are more users interested.

**Comment by alias1** [comment]
Yeah, that's fair. The annotations are pretty terrible, especially in a scala world, though the end result is nice if it works. If I end up cutting anything together for my project i'll through up the code for you.

**Comment by fuzzypantlets** [comment]
+1 for interest.

**Comment by cotyar** [comment]
+1 for interest

**Comment by aywengo** [comment]
+1 for interest

**Comment by aywengo** [comment]
Moved swagger annotations to the separate trait. Now routes look more readable, but splitting all directives to dedicated methods still tends to be ugly :P

**Comment by adamw** [comment]
Done in #116
