### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by grcasanova** [softwaremill/bootzooka#94]
The login system does not seem to work.

In the Promise, it does not send any data over the api.

```
let loggedUserPromise = $http.get('api/users').then(response => {
    loggedUser = response.data;
    return loggedUser;
  });
```

In the login part, the serialization does not work properly.
 ```
 userSessionService.login = user => $http.post('api/users', angular.toJson(user)).then(response => {
      loggedUser = response.data;
    return response.data;
  });
```

**Comment by hanskoff** [comment]
thanks for reporting the issue, but could you be more specific? tests are passing, app works like is it should (I see network requestes being transmitted with success http://bootzooka.softwaremill.com/#/) maybe you are experimenting some issues localy? did you pull the freshest changes?

**Comment by grcasanova** [comment]
The RememberMe is not implemented and the promise returns a "User not found" error since it is actually sending a blank request (no params).

**Comment by hanskoff** [comment]
This commit https://github.com/softwaremill/bootzooka/commit/1c9c9404 fixes the issue
